# Generated by Django 4.2.16 on 2024-09-19 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mi_aplicacion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conexion',
            name='peso',
            field=models.FloatField(default=1.0),
        ),
    ]
